### ISSUE TITLE
Add test of invoking function with multiple arguments

### ISSUE THREAD

**Issue by tapika** [FireFlyForLife/NeatReflection#4]
Tried to call argumented_function using two arguments parameters - and in my debugger arguments are passed in wrong order.

Not sure if this has to do anything with call conventions.

**Comment by FireFlyForLife** [comment]
Thank you for reporting this! This must have slipped through the cracks of my initial release :).

I debugged it for a bit and found it doesn't have to do with calling conventions, but that evaluating arguments of a function call is unspecified by the standard. I will add some tests and submit the fix tomorrow.

I also see you sent a PR with your fix, thanks you for the initiative! Though the fix I landed on doesn't look compatible with your solution. Which means I will likely close the PR. I hope you are okay with that, since you clearly put considerable time into a fix.

**Comment by tapika** [comment]
It's ok not to pick up my PR - I'm considering pass `const char*` and return same type as a hack. (I'll abort my PR).

What I've briefly analyzed - including string or `string_view` crashes `NeatReflectionCodeGen` - there is some support which needs to be added, but haven't analyzed in depth of what.

I've noticed also that fold expressions https://en.cppreference.com/w/cpp/language/fold does not take side on call convention, but suspect call convention defines the order of arguments. Suspect it's undocumented part of standard. :-)

I was considering to try out on creating neat reflection on something like `python-c++` bindings or `.net-c++` bindings, but then instead of operating on `std::any` need to use `PyObject* args` or `System::Object^[] args`.

**Comment by FireFlyForLife** [comment]
The fix for calling methods is in. I've created a new issue for the std::string crash. It seems I didn't support alias types yet!.

In terms of the specifics of this bug, it's actually not a folding expression but a pack expansion, so the normal function call, the order of evaluation of which is unspecified by the standard, [link](https://eel.is/c++draft/expr.call#example-4).

Again, I really appreciate you trying out the library :), I think that using this to bind `python-c++` would be quite cool. You could probably put the PyObject inside of std::any and see how that goes? I'm haven't used `python-c++` before.

**Comment by tapika** [comment]
Checked and `std::string` works at least as return parameter. 
Sounds like perfect.
Need to try out also via argument, also maybe including reference/pointer types.

`NeatReflection` does sounds like a library I want to play around in future. 
Thanks for coding such awesome library.
:)
